version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/client"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/server"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/worker"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/nginx"
    schedule:
      interval: "weekly"
